### ISSUE TITLE
README lost a lot of detail in last PR

### ISSUE THREAD

**Issue by asaba96** [Pitt-RAS/racecar#11]
README is less helpful and lost a lot of details. Is there anything missing that needs to be re-added or updated?

**Comment by nls5260** [comment]
I think it has to do with the fact that the branch that was merged in (magellan-motion? I believe) was modifications needed to run the simulation. This code is completely separate from the code run on the robot. So, we would probably have to go back in the git history and refactor it to allow for both sim option and non-sim option. Because, I think as of right now we are running on the sim code not the on robot code.

**Comment by asaba96** [comment]
Fixed in #13
