### ISSUE TITLE
Uncomment this line

### ISSUE THREAD

**Issue by asaba96** [Pitt-RAS/racecar#25]
https://github.com/Pitt-RAS/racecar/blob/695c273f0386a92a1e8c192e5c318aa3b82b22b5/src/magellan_motion/src/path_follower/path_follower.cpp#L49

**Comment by 4ndr3w** [comment]
Some background on why this is a thing -
Paths for magellan started at the start line and ended at the finish line. Since we walk through the array of points to find the one that's locally closest to us, it makes sense to start looking at the last one we found - instead of starting over every time the path is refreshed.

With the path from the new planner, we always get a new path that begins where we are - so we want to start looking for the closest point from the beginning.

**Comment by asaba96** [comment]
Addressed in #29
